### ISSUE TITLE
Import Error on Mac

### ISSUE THREAD

**Issue by trumanellis** [lanl/ExactPack#2]
I installed ExactPack with anaconda on my Mac and everything seemed to complete successfully, but when I try to import exactpack.solvers.riemann.Sod, I get the following error:

Traceback (most recent call last):
  File "ShockVV.py", line 16, in <module>
    from exactpack.solvers.riemann import Sod
  File "/Users/teellis/anaconda/lib/python2.7/site-packages/exactpack/solvers/riemann/__init__.py", line 99, in <module>
    from kamm import Riemann
  File "/Users/teellis/anaconda/lib/python2.7/site-packages/exactpack/solvers/riemann/kamm.py", line 5, in <module>
    from _kamm import riemann_kamm
ImportError: dlopen(/Users/teellis/anaconda/lib/python2.7/site-packages/exactpack/solvers/riemann/_kamm.so, 2): Library not loaded: /usr/local/gfortran/lib/libgfortran.3.dylib
  Referenced from: /Users/teellis/anaconda/lib/python2.7/site-packages/exactpack/solvers/riemann/_kamm.so
  Reason: image not found

**Comment by woodscn** [comment]
From your error message, it looks like python is not able to find your fortran library ("Library not loaded: /usr/local/gfortran/lib/libgfortran.3.dylib"). Can you confirm that you have a working fortran compiler on your computer?

**Comment by trumanellis** [comment]
I just tested gfortran on a simple hello world example and it seems to work fine.

**Comment by woodscn** [comment]
So much for the simple fix. Can you verify your version of gfortran, OS X, and Anaconda? Also, the output of "ls /usr/local/gfortran/lib/libgfort*"?

**Comment by trumanellis** [comment]
GNU Fortran (Homebrew GCC 6.3.0_1 --without-multilib) 6.3.0
OSX El Capitan Version 10.11.6
anaconda Command line client (version 1.6.0)

I installed gfortran through Homebrew, so I believe the equivalent location is 
ls /usr/local/Cellar/gcc/6.3.0_1/lib/gcc/6/libgfortran*
for which I get 
/usr/local/Cellar/gcc/6.3.0_1/lib/gcc/6/libgfortran.3.dylib /usr/local/Cellar/gcc/6.3.0_1/lib/gcc/6/libgfortran.dylib
/usr/local/Cellar/gcc/6.3.0_1/lib/gcc/6/libgfortran.a       /usr/local/Cellar/gcc/6.3.0_1/lib/gcc/6/libgfortran.spec

**Comment by woodscn** [comment]
Per the error I referenced above, it seems that Python is looking for libgfortran in /usr/local/gfortran/lib/. 

It seems that this may be an ongoing issue with homebrew: https://github.com/Homebrew/legacy-homebrew/issues/8539

What is the result of 
'''gfortran --print-file-name libgfortran.3.dylib'''

**Comment by trumanellis** [comment]
/usr/local/Cellar/gcc/6.3.0_1/lib/gcc/6/gcc/x86_64-apple-darwin15.6.0/6.3.0/../../../libgfortran.3.dylib

**Comment by woodscn** [comment]
That's definitely the problem. Whatever tools python uses to find the appropriate libraries are failing to locate the homebrew cellar. I'm rather surprised that homebrew didn't symlink the libraries to /usr/local/lib. Can you try `brew link gcc`, and see if they appear there?

**Comment by trumanellis** [comment]
I ran 
`brew unlink gcc && brew link gcc
`and got the following output:
```
Unlinking /usr/local/Cellar/gcc/6.3.0_1... 30 symlinks removed
Linking /usr/local/Cellar/gcc/6.3.0_1... 30 symlinks created
```

Running `brew doctor`
gave me the following warnings about anaconda:

```
Warning: Anaconda is known to frequently break Homebrew builds, including Vim and
MacVim, due to bundling many duplicates of system and Homebrew-available
tools.

If you encounter a build failure please temporarily remove Anaconda
from your $PATH and attempt the build again prior to reporting the
failure to us. Thanks!

Warning: "config" scripts exist outside your system or Homebrew directories.
`./configure` scripts often look for *-config scripts to determine if
software packages are installed, and what additional flags to use when
compiling and linking.

Having additional scripts in your path can confuse software installed via
Homebrew if the config script overrides a system or Homebrew provided
script of the same name. We found the following "config" scripts:
  /Users/teellis/anaconda/bin/curl-config
  /Users/teellis/anaconda/bin/freetype-config
  /Users/teellis/anaconda/bin/icu-config
  /Users/teellis/anaconda/bin/libpng-config
  /Users/teellis/anaconda/bin/libpng16-config
  /Users/teellis/anaconda/bin/python-config
  /Users/teellis/anaconda/bin/python2-config
  /Users/teellis/anaconda/bin/python2.7-config
  /Users/teellis/anaconda/bin/xml2-config
  /Users/teellis/anaconda/bin/xslt-config
```

**Comment by woodscn** [comment]
I've been trying to recreate your environment, but I'm stymied because homebrew doesn't seem to want to work with my older version of XCode. Unfortunately, that's tied to the MacOS version, which is controlled by IT. I'm contacting them, but it may take time.

One fix we have used internally is to simply install gcc from anaconda as well. If that works for your workflow, it should solve this problem. Alternatively, you can also clone the EP source and install it using the setup.py file. It will recompile all of the libraries on your machine, and Anaconda should have taken care of all of the Python dependencies.

**Comment by trumanellis** [comment]
I'm trying a different approach. I uninstalled homebrew and all it's packages and am trying to do everything through anaconda. I uninstalled anaconda and am starting from scratch. 
`conda install exactpack -c lanl-exactpack`
seemed to work correctly, but I'm still getting the error:
```
Traceback (most recent call last):
  File "ShockVV.py", line 16, in <module>
    from exactpack.solvers.riemann import Sod
  File "/Users/teellis/anaconda/lib/python2.7/site-packages/exactpack/solvers/riemann/__init__.py", line 99, in <module>
    from kamm import Riemann
  File "/Users/teellis/anaconda/lib/python2.7/site-packages/exactpack/solvers/riemann/kamm.py", line 5, in <module>
    from _kamm import riemann_kamm
ImportError: dlopen(/Users/teellis/anaconda/lib/python2.7/site-packages/exactpack/solvers/riemann/_kamm.so, 2): Library not loaded: /usr/local/gfortran/lib/libgfortran.3.dylib
  Referenced from: /Users/teellis/anaconda/lib/python2.7/site-packages/exactpack/solvers/riemann/_kamm.so
  Reason: image not found
```

I've tried various `conda install`s to fix this: gcc, gfortran, libgfortran, but nothing seems to work.

**Comment by woodscn** [comment]
Our usual build environment for Exactpack is to use XCode tools together with gfortran (installed via binary from https://gcc.gnu.org/wiki/GFortranBinaries). 

I'm going to recommend that you build from source for now, and see whether we can come up with a solution. We'll update the documentation to reflect this.

**Comment by trumanellis** [comment]
That worked, thanks!

**Comment by woodscn** [comment]
Possibly a result of Numpy 1.12.0 breaking f2py. Documentation now suggests a build from source rather than a conda install for exactpack. Will see if conda build can be reactivated in the future.
